name: Code_linter Bash Scripts  # Workflow name

on:
  push:
    branches: 
      - main
      - data-v1.0
      - data-v1.1
      - data-v1.2
  pull_request: 
    branches: 
      - main
      - data-v1.0
      - data-v1.1
      - data-v1.2

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: true
           
